# Summary: TFQ continuous integration workflow for checking C++ files.
#
# This workflow runs clang-formmat. It only examines C++ and protobuf files.
# It can be invoked manually using the "Run workflow" button on the page at
# https://github.com/tensorflow/quantum/actions/workflows/lint-c++-files.yaml
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

name: C++ & protobuf file checks
run-name: >
  C++ & protobuf lint & format checks for ${{github.event_name}}
  by ${{github.triggering_actor}}

env:
  # Version of clang-format to use. Can be overridden with workflow_dispatch.
  # Note: as of 2025-01-14, v. 18 is the latest available on Ubuntu 24.04.
  clang_format_ver: '18'

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - '**.cc'
      - '**.h'
      - '**.proto'

  push:
    paths:
      - '**.cc'
      - '**.h'
      - '**.proto'

  # Allow manual invocation, with options that might be useful for debugging.
  workflow_dispatch:
    inputs:
      clang_format_ver:
        description: 'clang-format version:'
        type: string

# Cancel previously-started but still active workflow runs on the same branch.
concurrency:
  group: ${{github.workflow}}-${{github.event.pull_request.number||github.ref}}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write

jobs:
  format:
    name: Check the format of C++ and Protobuf files
    runs-on: ubuntu-24.04
    steps:
      - name: Count how many git commits need to be fetched
        id: count
        env:
          commits: ${{ toJson(github.event.commits) }}
        run: |
          printf "%s" "$commits" > ./commits.txt
          first=$(jq 'sort_by(.timestamp) | first | .id' < ./commits.txt)
          echo first_commit="$first" >> "$GITHUB_OUTPUT"
          num_commits="$(jq length < ./commits.txt)"
          (( num_commits++ ))
          echo num_commits="$num_commits" >> "$GITHUB_OUTPUT"

      - name: Check out a copy of the TFQ git repository
        uses: actions/checkout@v4
        with:
          fetch-depth: ${{steps.count.outputs.num_commits}}

      - name: Run clang-format on C++ and Protobuf files
        run: |
          set -x
          version="${{inputs.clang_format_ver || env.clang_format_ver}}"
          sha="$(git rev-parse ${{steps.count.outputs.first_commit}}^)"
          git clang-format-$version --style google --diff \
            --commit $sha^ > diff.out 2>&1
          exit_code=$?
          if (( exit_code == 1 )) && [[ -s ./diff.out ]]; then
            # Write output both here and to the job summary.
            TERM=xterm-color
            bo=$'\e[1m'
            bl=$'\e[38;5;117m'
            rs=$'\e[0m'
            hi="👋🏻"
            u="https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}"
            echo "$hi ${bl}Visit $bo$u${rs}$bl for formatted diff output$rs $hi"
            echo "::group::clang-format output"
            cat diff.out
            echo "::endgroup::"
            # shellcheck disable=SC2006
            {
            echo "## Output from `clang-format`"
            echo ""
            echo '```diff'
            echo "$(< diff.out)"
            echo '```'
            } >> "$GITHUB_STEP_SUMMARY"
          fi
          exit $exit_code
