name: Lint & format checks

on:
  pull_request:

concurrency:
  group: ${{github.ref}}-${{github.workflow}}
  cancel-in-progress: true

jobs:
  python:
    name: Python files
    runs-on: ubuntu-22.04
    steps:
      - name: Check out a copy of the TFQ git repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10.15'

      - name: Install Pylint
        run: |
          python -m pip install --upgrade pip
          python -m pip install pylint

      - name: Lint all
        run: |
          pylint .

  yaml:
    name: YAML files
    runs-on: ubuntu-22.04
    steps:
      - name: Check out a copy of the TFQ git repository
        uses: actions/checkout@v4

      - name: Install yamllint
        run: |
          sudo apt-get install yamllint

      - name: Lint all
        run: |
          yamllint .

